kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: myapi
  namespace: meet14764-dev
  uid: 51d9b1dd-87d2-4383-bb7e-2d72fcb6cd14
  resourceVersion: '1452339582'
  generation: 2
  creationTimestamp: '2022-06-30T07:53:32Z'
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2022-06-30T07:53:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:imageChangeTriggers': {}
          'f:lastVersion': {}
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2022-06-30T07:53:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:runPolicy': {}
          'f:source':
            'f:git':
              .: {}
              'f:ref': {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:sourceStrategy':
              .: {}
              'f:from': {}
            'f:type': {}
          'f:triggers': {}
spec:
  nodeSelector: null
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-17-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/harmeet2401/MyApi.git'
      ref: main
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 1
  imageChangeTriggers:
    - lastTriggeredImageID: >-
        image-registry.openshift-image-registry.svc:5000/openshift/java@sha256:210e5ce062df2cc601fb8ce4be4848fe25d87238cd44aa4abe833eb3d4893640
      from:
        namespace: openshift
        name: 'java:openjdk-17-ubi8'
      lastTriggerTime: null
