kind: Service
apiVersion: v1
metadata:
  name: api-rest
spec:
  clusterIP: 172.30.211.20
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.211.20
  type: ClusterIP
  selector:
    app: api-rest
    deploymentconfig: api-rest
status:
  loadBalancer: {}
